# Alpha Production Test Configuration
# Phase 3 production testing: 2 realizations with primary redshifts

production:
  name: "alpha"
  version: "v1.0"
  description: "Alpha production test for Phase 3 deployment: 2 realizations (ph3000, ph3001) with 12 primary redshifts"
  tags: ["phase3", "alpha", "production-test", "primary-redshifts"]

science:
  cosmology: "AbacusSummit"
  redshifts: [0.2, 0.25, 0.3, 0.4, 0.5, 0.8, 1.1, 1.4, 1.7, 2.0, 2.5, 3.0]
  realizations:
    start: 3000
    count: 2
    step: 1
  catalog_params:
    magnitude_limit: 25.0
    area_deg2: 1000.0

execution:
  job_type: "gpu_intensive"
  batch_size: 1
  timeout_hours: 0.167
  retry_policy:
    max_retries: 3
    backoff_multiplier: 2.0
    initial_delay_minutes: 5.0

# GPU resources for alpha testing - override job_type defaults
resources:
  nodes_per_job: 2
  tasks_per_node: 64
  memory_gb: 128.0
  gpus_per_node: 4
  constraint: "gpu"
  partition: "gpu"

outputs:
  base_path: "/global/cfs/cdirs/m4943/Simulations/covariance_mocks"
  structure: "hierarchical"
  compression: "gzip"
  cleanup_policy:
    keep_logs_days: 14
    keep_intermediate: true
    archive_completed: false