# Production Campaign Configuration
# Full-scale campaign for generating covariance mocks

campaign:
  name: "covariance_v1"
  version: "v1.0"
  description: "Production campaign for covariance mock generation with 2000 realizations across 20 redshift snapshots"
  tags: ["production", "covariance", "abacus_summit"]

science:
  cosmology: "AbacusSummit"
  redshifts: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.2, 2.5, 3.0, 4.0]
  realizations:
    start: 0
    count: 2000
    step: 1
  catalog_params:
    magnitude_limit: 25.0
    area_deg2: 5000.0

execution:
  job_type: "cpu_intensive"
  batch_size: 200
  timeout_hours: 24.0
  retry_policy:
    max_retries: 3
    backoff_multiplier: 2.0
    initial_delay_minutes: 10.0

# Use default NERSC resources for production
# (will be loaded from config/defaults/nersc.yaml)

outputs:
  base_path: "/global/cfs/cdirs/m4943/Simulations/covariance_mocks/campaigns"
  structure: "hierarchical"
  compression: "gzip"
  cleanup_policy:
    keep_logs_days: 90
    keep_intermediate: false
    archive_completed: true